  services:
    mysql:
      image: mysql:latest
      volumes:
        - mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: db_2
        MYSQL_USER: user
        MYSQL_PASSWORD: user123
        MYSQL_TCP_PORT: 3307
      ports:
        - '3307:3307'
      networks:
        - spring-shop-network

    webapp:
      image: jakubmarjankowski/shop-statistic:1.0
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      ports:
        - '8080:8080'
      networks:
        - spring-shop-network
  volumes:
    mysql:
    mysql-test:

  networks:
    spring-shop-network: